#!/usr/bin/env tsx
import { mkdtemp, mkdir, writeFile, readFile, chmod, rm } from "node:fs/promises";
import { join, resolve, dirname } from "node:path";
import { tmpdir } from "node:os";
import { setTimeout as delay } from "node:timers/promises";
import { PiRpcClient } from "../test/e2e/helpers/rpc-client.ts";
import { childJournalPath, safeSessionId, parseFiniteEnv, parseLiveModel, parseLfJournal, collectEnvelopes, hasDurableFinal, validateLiveGraph } from "./live-mechanistic-e2e-support.ts";

async function stopClient(client:PiRpcClient):Promise<{exit:number|null;category:string}>{const c=new AbortController();client!.kill("SIGTERM");const result=await Promise.race([client!.waitForExit().then(code=>{c.abort();return {kind:"exit" as const,code}}).catch(()=>{c.abort();return {kind:"exit-error" as const}}),delay(5000,undefined,{signal:c.signal}).then(()=>({kind:"deadline" as const}))]);if(result.kind==="exit-error"){return {exit:null,category:"exit-error"};}if(result.kind==="deadline"){client!.kill("SIGKILL");return {exit:await client!.waitForExit(),category:"forced-kill"};}return {exit:result.code,category:"term"};}
const model = process.env.LIVE_MODEL; const agentDir = process.env.PI_CODING_AGENT_DIR ?? join(process.env.HOME ?? tmpdir(), ".pi", "agent");
const timeout = parseFiniteEnv(process.env.LIVE_TIMEOUT_MS, 240_000); parseLiveModel(model);
const root = await mkdtemp(join(tmpdir(), "pi-mechanistic-live-")); await chmod(root, 0o700);
const worker = `evidence-worker.nonce@${model!.split("/").at(-1)}.com`; const main = `main@${model!.split("/").at(-1)}.com`; const mechanistic="evidence.nonce@mechanistic.com";
const script=join(root,"evidence.py"); await writeFile(join(root,"evidence.txt"),"NONCE-"+Math.random().toString(36).slice(2,12)); await writeFile(script,`import json\nfrom pathlib import Path\nfrom pi_mechanistic import arguments,invocation,send_email,success\na=arguments(); n=Path('evidence.txt').read_text().strip(); j=invocation()['jobId']; ack=send_email(a['notify_to'],'MECHANISTIC_EVIDENCE','Inspect evidence and send MECHANISTIC_CHAIN_COMPLETE to ${main} with Structured: '+json.dumps({'nonce':n,'jobId':j},separators=(',',':'))); assert ack['accepted']; success('evidence processed: '+n)\n`); await writeFile(join(root,"subagents.json"),JSON.stringify({mechanisticPrograms:{evidence:{python:"/usr/bin/python3",script,cwd:root,allowedCallers:["main"]}}}));
let client:PiRpcClient|undefined; let startupError:string|undefined; let journalEvents:any[]=[]; let finalObserved=false; let shutdown="failure"; const controller=new AbortController(); const timeoutController=new AbortController();
try { client=PiRpcClient.launch({cwd:root,agentDir,model:model!,extensions:[resolve("./src/index.ts")],env:{}}); } catch { startupError="Pi startup or get_state failed"; } let sessionId:string|undefined; let journal:string|undefined; try { const state=await client!.getState(); if(state.success!==true) throw new Error("get_state failed"); sessionId=safeSessionId((state.data as {sessionId?:unknown}).sessionId); journal=childJournalPath(agentDir,sessionId); } catch { startupError="Pi startup or get_state failed"; } const journalPath=journal; const mark=client?.mark()??0;
let pollError:string|undefined;
const prompt=`You MUST make one send_email tool call before any final answer. Call it exactly once to ${mechanistic} as a notification (requires_response:false), with JSON body {"notify_to":"${worker}"}. Do not merely describe or wait. No reply_to or completion fields. The worker must then call send_email(to='${main}', subject='MECHANISTIC_CHAIN_COMPLETE', message=<exact JSON {nonce,jobId}>, requires_response=false), with no reply/completion.`;
const poll=(async()=>{while(!controller.signal.aborted&&!startupError){try{journalEvents=parseLfJournal(await readFile(journalPath!,"utf8"));if(hasDurableFinal(collectEnvelopes(journalEvents),worker,main)&&client?.events().some(e=>e.type==="agent_settled")){finalObserved=true;shutdown="completed";return;}}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT"||/truncated/.test(String(error))){await delay(250,undefined,{signal:controller.signal});continue;} pollError="journal polling failed";return;} await delay(250,undefined,{signal:controller.signal});}})();
let childExitCode:number|null=null; let timedOut=false; try { if(startupError) throw new Error("startup failure"); if(!client) throw new Error("startup failure"); await client.prompt(prompt); const timer=delay(timeout,undefined,{signal:timeoutController.signal}).then(()=>{timedOut=true;shutdown="timeout";}); await Promise.race([poll,timer]); if(finalObserved) { timeoutController.abort(); await client!.close(); } else { timeoutController.abort(); controller.abort(); shutdown=timedOut?"timeout":"poll-error"; childExitCode=client?(await stopClient(client)).exit:null; } } catch(error) { pollError=error instanceof Error?error.message:"lifecycle error"; shutdown="error"; controller.abort(); childExitCode=client?(await stopClient(client)).exit:null; } finally { controller.abort(); await poll.catch(error=>{pollError=error instanceof Error?error.message:"poll error";}); childExitCode=childExitCode??(client?await client.waitForExit().catch(()=>null):null); }
try{journalEvents=parseLfJournal(await readFile(journalPath!,"utf8"));}catch{pollError=pollError??"final journal unavailable or malformed";}
const rpcSummary={getStateResponses:client?.events().filter(e=>e.type==='response'&&e.command==='get_state').length??0,promptResponses:client?.events().filter(e=>e.type==='response'&&e.command==='prompt').length??0,agentStarts:client?.events().filter(e=>e.type==='agent_start').length??0,agentEnds:client?.events().filter(e=>e.type==='agent_end').length??0,settled:client?.events().filter(e=>e.type==='agent_settled').length??0,toolEnds:client?.events().filter(e=>e.type==='tool_execution_end').map(e=>({toolName:typeof e.toolName==='string'?e.toolName:'other',isError:e.isError===true}))??[],extensionErrors:client?.events().filter(e=>e.type==='extension_error').length??0};
const envelopes=collectEnvelopes(journalEvents); const validation=validateLiveGraph({events:journalEvents,worker,main,mechanistic,childExitCode,durableFinalObserved:finalObserved,mainSettled:client?.events().some(e=>e.type==="agent_settled"),pollError:pollError||startupError||(timedOut?"timeout":undefined),timedOut}); const runnerExitCode=validation.ok&&childExitCode===0?0:1; const out=resolve(process.env.LIVE_EVIDENCE_DIR??".test-workspaces/mechanistic-subagents"); await mkdir(out,{recursive:true}); const log=join(out,`live-mechanistic-${Date.now()}.json`); await writeFile(log,JSON.stringify({model,rpcSummary,runnerExitCode,childExitCode,shutdown,sessionId,envelopes:envelopes.map(e=>({id:e.id,from:e.from,to:e.to,subject:e.subject,kind:e.kind,requiresResponse:e.requiresResponse})),validation},null,2)); const namespace=journalPath?dirname(journalPath):undefined; if(runnerExitCode===0){if(namespace)await rm(namespace,{recursive:true,force:true});await rm(root,{recursive:true,force:true});}else{await chmod(root,0o700);if(namespace)try{await chmod(namespace,0o700);}catch{} console.error(`preserved evidence project: ${root}; namespace: ${namespace}`);} console.log(JSON.stringify({passed:runnerExitCode===0,model,runnerExitCode,childExitCode,log})); process.exitCode=runnerExitCode;
