#!/usr/bin/env tsx
import { mkdtemp, mkdir, writeFile, readFile, chmod, rm } from "node:fs/promises";
import { join, resolve, dirname } from "node:path";
import { tmpdir } from "node:os";
import { setTimeout as delay } from "node:timers/promises";
import { PiRpcClient } from "../test/e2e/helpers/rpc-client.ts";
import { childJournalPath, parseFiniteEnv, parseLiveModel, parseLfJournal, collectEnvelopes, hasDurableFinal, validateLiveGraph } from "./live-mechanistic-e2e-support.ts";

const model = process.env.LIVE_MODEL; const agentDir = process.env.PI_CODING_AGENT_DIR ?? join(process.env.HOME ?? tmpdir(), ".pi", "agent");
const timeout = parseFiniteEnv(process.env.LIVE_TIMEOUT_MS, 240_000); parseLiveModel(model);
const root = await mkdtemp(join(tmpdir(), "pi-mechanistic-live-")); await chmod(root, 0o700);
const worker = `evidence-worker.nonce@${model!.split("/").at(-1)}.com`; const main = `main@${model!.split("/").at(-1)}.com`; const mechanistic="evidence.nonce@mechanistic.com";
const script=join(root,"evidence.py"); await writeFile(join(root,"evidence.txt"),"NONCE-"+Math.random().toString(36).slice(2,12)); await writeFile(script,`import json\nfrom pathlib import Path\nfrom pi_mechanistic import arguments,invocation,send_email,success\na=arguments(); n=Path('evidence.txt').read_text().strip(); j=invocation()['jobId']; ack=send_email(a['notify_to'],'MECHANISTIC_EVIDENCE','Inspect evidence and send MECHANISTIC_CHAIN_COMPLETE to ${main} with Structured: '+json.dumps({'nonce':n,'jobId':j},separators=(',',':'))); assert ack['accepted']; success('evidence processed: '+n)\n`); await writeFile(join(root,"subagents.json"),JSON.stringify({mechanisticPrograms:{evidence:{python:"/usr/bin/python3",script,cwd:root,allowedCallers:["main"]}}}));
const client=PiRpcClient.launch({cwd:root,agentDir,model:model!,extensions:[resolve("./src/index.ts")],env:{}}); let journalEvents:any[]=[]; let finalObserved=false; let shutdown="failure"; const controller=new AbortController();
const state=await client.getState(); const sessionId=String((state.data as any).sessionId); const journal=childJournalPath(agentDir,sessionId); const mark=client.mark();
const prompt=`Use send_email exactly once to invoke ${mechanistic} with requires_response:false and JSON {"notify_to":"${worker}"}. The worker must send exact subject MECHANISTIC_CHAIN_COMPLETE to ${main} with structured nonce/job JSON. No replies/completion.`;
const poll=(async()=>{while(!controller.signal.aborted){try{journalEvents=parseLfJournal(await readFile(journal,"utf8"));if(hasDurableFinal(collectEnvelopes(journalEvents),worker,main)&&client.events().some(e=>e.type==="agent_settled")){finalObserved=true;shutdown="completed";return;}}catch{} await delay(250,undefined,{signal:controller.signal});}})();
let childExitCode:number|null=null; try{await client.prompt(prompt); await Promise.race([client.waitForSettlement(mark,timeout),delay(timeout,undefined,{signal:controller.signal}).then(()=>{shutdown="timeout";})]); if(finalObserved) await client.close(); else {controller.abort();client.kill("SIGTERM");childExitCode=await client.waitForExit();}}catch{shutdown="error";controller.abort();client.kill("SIGTERM");} finally {controller.abort();await poll.catch(()=>undefined);childExitCode=childExitCode??await client.waitForExit().catch(()=>null);}
try{journalEvents=parseLfJournal(await readFile(journal,"utf8"));}catch{}
const envelopes=collectEnvelopes(journalEvents); const validation=validateLiveGraph({events:journalEvents,worker,main,mechanistic,childExitCode,durableFinalObserved:finalObserved,mainSettled:client.events().some(e=>e.type==="agent_settled"),pollError:undefined}); const runnerExitCode=validation.ok&&childExitCode===0?0:1; const out=resolve(process.env.LIVE_EVIDENCE_DIR??".test-workspaces/mechanistic-subagents"); await mkdir(out,{recursive:true}); const log=join(out,`live-mechanistic-${Date.now()}.json`); await writeFile(log,JSON.stringify({model,runnerExitCode,childExitCode,shutdown,sessionId,envelopes:envelopes.map(e=>({id:e.id,from:e.from,to:e.to,subject:e.subject,kind:e.kind,requiresResponse:e.requiresResponse})),validation},null,2)); if(runnerExitCode===0){await rm(root,{recursive:true,force:true});}else{await chmod(root,0o700);console.error(`preserved evidence project: ${root}`);} console.log(JSON.stringify({passed:runnerExitCode===0,model,runnerExitCode,childExitCode,log})); process.exitCode=runnerExitCode;
