import { parseMailEvent, type MailEvent } from "../src/mail-store.ts";

export interface LiveGraphInput { events: MailEvent[]; worker: string; main: string; mechanistic: string; }
export interface LiveValidation { ok: boolean; reasons: string[]; envelopes: number; jobId?: string; outcomeId?: string; }
export function parseFiniteEnv(value: string|undefined, fallback:number, min=30_000, max=900_000): number { const n=value===undefined||value===""?fallback:Number(value); if(!Number.isSafeInteger(n)||n<min||n>max) throw new Error(`timeout must be an integer from ${min} to ${max}`); return n; }
export function parseLiveModel(value:string|undefined): {provider:string;modelId:string} { if(!value) throw new Error("LIVE_MODEL is required"); const i=value.indexOf("/"); if(i<=0||i===value.length-1) throw new Error("LIVE_MODEL must use provider/model"); return {provider:value.slice(0,i),modelId:value.slice(i+1)}; }
export function parseLfJournal(text:string): MailEvent[] { if(text.length===0)return []; if(!text.endsWith("\n")) throw new Error("truncated journal record"); return text.split("\n").filter(Boolean).map(line=>parseMailEvent(JSON.parse(line))); }
export function collectEnvelopes(events:MailEvent[]): any[] { const map=new Map<string,any>(); for(const e of events){ const email=("email" in e)?e.email:undefined; if(email)map.set(email.id,email); } return [...map.values()]; }
export function hasDurableFinal(envelopes:any[],worker:string,main:string):boolean { return envelopes.some(e=>e.from===worker&&e.to===main&&e.kind==='notification'&&e.requiresResponse===false&&e.inReplyTo===undefined&&e.subject==='MECHANISTIC_CHAIN_COMPLETE'); }
export function validateLiveGraph(input:LiveGraphInput):LiveValidation { const reasons:string[]=[]; const env=collectEnvelopes(input.events); const invocation=env.find(e=>e.from===input.main&&e.to===input.mechanistic); const workerFinal=env.find(e=>e.from===input.worker&&e.to===input.main); const jobs=input.events.filter((e):e is Extract<MailEvent,{type:'job.terminal'}>=>e.type==='job.terminal'); const job=(jobs[0] as any)?.job; const outcome=job&&env.find(e=>e.id===job.outcomeMailId); if(env.length!==4)reasons.push('expected exactly four envelopes'); if(!invocation)reasons.push('missing invocation'); if(!job||job.id!==invocation?.id)reasons.push('job is not linked to invocation'); if(!workerFinal)reasons.push('missing worker final'); if(!outcome||outcome.to!==input.main)reasons.push('missing automatic outcome'); for(const e of env){if(e.kind!=='notification'||e.requiresResponse!==false||e.inReplyTo!==undefined||e.completion!==undefined)reasons.push('non-notification graph envelope')} if(job?.result!=='success'||job.cleanup?.state!=='confirmed')reasons.push('runtime or cleanup failure'); return {ok:reasons.length===0,reasons,envelopes:env.length,jobId:job?.id,outcomeId:job?.outcomeMailId}; }